responsive_video.responsive_video_style.*:
  type: config_entity
  label: Responsive Video Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

responsive_video.video_style.*:
  type: config_entity
  label: Video Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

responsive_video.video_format.*:
  type: config_entity
  label: Video Format
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

responsive_video.settings:
  type: config_object
  label: 'Responsive Video settings'
  mapping:
    converter_plugin:
      type: string
      label: 'Selected converter plugin'
    converter_plugin_configuration:
      type: sequence
      label: 'Converter plugin configuration'
      sequence:
        type: string

responsive_video.responsive_video_style_size.*:
  type: config_entity
  label: Responsive Video Style Size
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
