responsive_video.responsive_video_style.*:
  type: config_entity
  label: Responsive Video Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

responsive_video.video_style.*:
  type: config_entity
  label: Video Style
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
